permalink: /:year/:month/:day/:title
timezone: Japan
plugins: [jekyll-paginate,jekyll-paginate-multiple]
#paginate: 10
paginate_multiple:
  - paginate: 10
    paginate_path: 'blog_list/page:num'
    sub_dir: 'blog'
  - paginate: 7
    paginate_path: 'works_list/page:num/'
    sub_dir: 'works'
    